modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="kaka"
version="${file.jarVersion}"
displayName="Kaka"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="kaka.png" #optional
credits="Thanks Matik for kaka" #optional
# A text field displayed in the mod UI
authors="igentuman" #optional
description='''
Adds some kaka into game
'''
[[dependencies.kaka]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.kaka]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
